<?php

namespace App\Models\I4;

use Illuminate\Database\Eloquent\Model;

class Persona extends Model
{
    protected $connection = 'mysql';
    protected $table      = 'Persona';

    protected $fillable = [
        "version",
        "Nombres",
        "ApPat",
        "ApMat",
        "ApEsp",
        "Persona",
        "Alias",
        "NumDocId",
        "DepDocId",
        "NivelReserva",
        "EsPersonaJuridica",
        "DenunciasAnterioresDelito",
        "EsDenunciado",
        "EsDenunciante",
        "EsVictima",
        "EsTestigo",
        "Foto",
        "CreatorUser",
        "CreatorFullName",
        "CreationDate",
        "CreationIP",
        "UpdaterUser",
        "UpdaterFullName",
        "UpdaterDate",
        "UpdaterIP",
        "FechaNac",
        "Edad",
        "NomMuniNac",
        "ProfesionOficio",
        "DirDom",
        "ZonaDom",
        "NomMuniDom",
        "TelDom",
        "CelularDom",
        "EMailPrivado",
        "EmpresaTrab",
        "Cargo",
        "DirTrab",
        "ZonaTrab",
        "NomMuniTrab",
        "TelTrab",
        "CelularTrab",
        "EMailTrab",
        "RepresentanteLegalNoRegistrado",
        "DirNotif",
        "ZonaNotif",
        "TelNotif",
        "CelularNotif",
        "EMailNotif",
        "PuntosMapa",
        "Caso",
        "TipoDocId",
        "Nacionalidad",
        "Sexo",
        "EstadoCivil",
        "EstadoPersona",
        "EstadoLibertad",
        "EstadoMental",
        "TipoFamilia",
        "RelacionVictima",
        "RelacionDenunciado",
        "RelacionDenunciante",
        "DelitoPrincipal",
        "GrupoVulnerable",
        "PuebloOriginario",
        "TipoFuncionarioPublico",
        "ClaseDelito",
        "FinesTrata",
        "MuniNac",
        "PaisNac",
        "MuniDom",
        "PaisDom",
        "MuniTrab",
        "PaisTrab",
        "MuniNotif",
        "NivelEducacion",
        "ColorTez",
        "ColorOjos",
        "ColorCabello",
        "Abogado",
        "TipoDomicilioProcesal",
        "CertificacionSegip",
        "Estatura",
        "Peso",
        "SeniasParticulares",
        "NombrePandilla",
        "NombreLiderPandilla",
        "DirSedePandilla",
        "ZonaPandilla",
        "NotasPandilla",
        "Tentativa",
        "VictimaFallecida",
        "CodigoElectricidadDom",
        "CodigoElectricidadTrab",
        "CodigoElectricidadNotif",
        "PersonaFallecida"
    ];

    protected $guarded  = [];
}