<?php

namespace App\Models\I4;

use Illuminate\Database\Eloquent\Model;

class Persona extends Model
{
    protected $connection = 'mysql';
    protected $table      = 'Persona';

    protected $fillable = [
        "version",
        "Nombres",
        "ApPat",
        "ApMat",
        "ApEsp",
        "Persona",
        "Alias",
        "NumDocId",
        "DepDocId",
        "NivelReserva",
        "EsPersonaJuridica",
        "DenunciasAnterioresDelito",
        "EsDenunciado",
        "EsDenunciante",
        "EsVictima",
        "EsTestigo",
        "Foto",
        "CreatorUser",
        "CreatorFullName",
        "CreationDate",
        "CreationIP",
        "UpdaterUser",
        "UpdaterFullName",
        "UpdaterDate",
        "UpdaterIP",
        "FechaNac",
        "Edad",
        "NomMuniNac",
        "ProfesionOficio",
        "DirDom",
        "ZonaDom",
        "NomMuniDom",
        "TelDom",
        "CelularDom",
        "EMailPrivado",
        "EmpresaTrab",
        "Cargo",
        "DirTrab",
        "ZonaTrab",
        "NomMuniTrab",
        "TelTrab",
        "CelularTrab",
        "EMailTrab",
        "RepresentanteLegalNoRegistrado",
        "DirNotif",
        "ZonaNotif",
        "TelNotif",
        "CelularNotif",
        "EMailNotif",
        "PuntosMapa",
        "Caso",
        "TipoDocId",
        "Nacionalidad",
        "Sexo",
        "EstadoCivil",
        "EstadoPersona",
        "EstadoLibertad",
        "EstadoMental",
        "TipoFamilia",
        "RelacionVictima",
        "RelacionDenunciado",
        "RelacionDenunciante",
        "DelitoPrincipal",
        "GrupoVulnerable",
        "PuebloOriginario",
        "TipoFuncionarioPublico",
        "ClaseDelito",
        "FinesTrata",
        "MuniNac",
        "PaisNac",
        "MuniDom",
        "PaisDom",
        "MuniTrab",
        "PaisTrab",
        "MuniNotif",
        "NivelEducacion",
        "ColorTez",
        "ColorOjos",
        "ColorCabello",
        "Abogado",
        "TipoDomicilioProcesal",
        "CertificacionSegip",
        "Estatura",
        "Peso",
        "SeniasParticulares",
        "NombrePandilla",
        "NombreLiderPandilla",
        "DirSedePandilla",
        "ZonaPandilla",
        "NotasPandilla",
        "Tentativa",
        "VictimaFallecida",
        "CodigoElectricidadDom",
        "CodigoElectricidadTrab",
        "CodigoElectricidadNotif",
        "PersonaFallecida",

        "triton_modificado",
        "recinto_carcelario_id",
        "dp_estado",
        "dp_semaforo",
        "dp_fecha_detencion_preventiva",
        "dp_fecha_conclusion_detencion",
        "dp_etapa_gestacion_estado",
        "dp_etapa_gestacion_semana",
        "dp_enfermo_terminal_estado",
        "dp_enfermo_terminal_tipo",
        "dp_persona_mayor_65",
        "dp_madre_lactante_1",
        "dp_madre_lactante_1_fecha_nacimiento_menor",
        "dp_custodia_menor_6",
        "dp_custodia_menor_6_fecha_nacimiento_menor",
        "dp_mayor_3",
        "dp_minimo_previsto_delito",
        "dp_pena_menor_4",
        "dp_delito_pena_menor_4",
        "dp_delito_patrimonial_menor_6",
        "dp_etapa_preparatoria_dias_transcurridos_estado",
        "dp_etapa_preparatoria_dias_transcurridos_numero",

        "created_at",
        "update_at",
        "estado_segip",
        "reincidencia"
    ];

    protected $guarded  = [];
}